apiVersion: v1
kind: Template
metadata:
  name: mq-server-template
  annotations:
    openshift.io/display-name: IBM MQ Persistent Template
    description: Creates a MQ Server configuration and with a persistent volume mounted on /mnt/mqm
    tags: mq-server-app
  labels:
    app: mq-server-template
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-${NAME}-mqm
    labels:
      app: mq-${NAME}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${MQM_STORAGE_SIZE}
    storageClassName: ${STORAGE_CLASS_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}-mq-svc
    labels:
      app: mq-${NAME}
  spec:
    type: ClusterIP
    ports:
    - port: 9443
      name: console-https
    - port: 1414
      name: qmgr
    - targetPort: 9157
      port: 9157
      protocol: TCP
      name: prometheus
    selector:
      app: mq-${NAME} 	
- apiVersion: apps/v1
  kind: Route
  apiVersion: v1
  metadata:
    name: ${NAME}-mq-route
    labels:
      app: mq-${NAME}
    name: ${NAME}-mq-route
  spec:
    host: ${NAME}.${WILDCARD_DOMAIN}
    to:
      kind: Service
      name: ${NAME}-mq-svc
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: mq-${NAME}
    name: ${NAME}-mq-server
  spec:
    selector:
      matchLabels:
        app: mq-${NAME} 
    template:
      metadata:
        labels:
          app: mq-${NAME}
      spec:
        containers:
          - name: qmgr
            image: ${MQ_IMAGE}
            imagePullPolicy: Always
            terminationMessagePath: "/run/termination-log"
            ports:
            - containerPort: 1414
            - containerPort: 9443
            - containerPort: 9157
            env:
            - name: LICENSE
              value: "accept"
            - name: MQ_QMGR_NAME
              value: ${MQ_QMGR_NAME}
            - name: MQ_MULTI_INSTANCE
              value: "${MQ_MULTI_INSTANCE}"
            - name: LOG_FORMAT
              value: "${LOG_FORMAT}"
            volumeMounts:
            - mountPath: "/mnt/mqm"
              name: pvc-${NAME}-mqm
            resources:
              limits:
                memory: "${MEMORY_LIMIT}"	  
                cpu: "${CPU_LIMIT}"	  
              requests:
                memory: ${MEMORY_LIMIT}  
                cpu: ${CPU_LIMIT}	
        volumes:
        - name: pvc-${NAME}-mqm
          persistentVolumeClaim:
            claimName: pvc-${NAME}-mqm	 

parameters:
- description: The name assigned to all of the objects defined in this template.
  displayName: Name
  name: NAME
  required: true
- description: MQ_QMGR_NAME .
  displayName: QMGR NAME
  name: MQ_QMGR_NAME
  value: ACEQM1
  required: true
- description: The image name .
  displayName: MQImage
  name: MQ_IMAGE
  value: "registry.ixpress.icicibank.com:5000/ibm-ace-gold-prod"
  required: true
- description: MQ Multi Instace .
  displayName: MqMultiInstace
  name: MQ_MULTI_INSTANCE
  value: "false" 
- description: Shared File Storage size for MQ. Specify size in Mi,Gi
  displayName: StorageSize
  name: MQM_STORAGE_SIZE
  value: 256Mi
- description: Storage Class Name used for creating Shared File Storage
  displayName: StorageClassName
  name: STORAGE_CLASS_NAME
  value: managed-nfs-storage
- description: Wildcard domain name for creating the route
  displayName: WildcardDomain
  name: WILDCARD_DOMAIN
  value: apps.nonprod.icicibankltd.com
- description: The Log Format
  displayName: LogFormat
  name: LOG_FORMAT
  value: "basic"
- description: Memory Limit Of MQ
  displayName: MemoryLimt
  name: MEMORY_LIMIT
  value: 512Mi
- description: CPU Limit Of MQ
  displayName: CpuLimit
  name: CPU_LIMIT  
  value: 500m 
